import requests
from typing import List, Dict, Any
from functools import lru_cache
from config import NOTION_HEADERS

BASE_URL = "https://api.notion.com/v1"

@lru_cache(maxsize=1)
def get_integration_user_id() -> str:
    """
    Returns the Notion integration user id for the current token.
    Used to trace whether blocks were generated by this integration.
    """
    try:
        url = f"{BASE_URL}/users/me"
        response = requests.get(url, headers=NOTION_HEADERS)
        response.raise_for_status()
        data = response.json()
        return data.get("id", "")
    except Exception:
        return ""

def get_block(block_id: str) -> Dict[str, Any]:
    """获取单个块的完整信息（含 rich_text）。"""
    url = f"{BASE_URL}/blocks/{block_id}"
    response = requests.get(url, headers=NOTION_HEADERS)
    response.raise_for_status()
    return response.json()

def get_page_blocks(block_id: str) -> List[Dict[str, Any]]:
    """递归获取页面或块的所有子块。 (Handles pagination + nested children)"""
    blocks = []
    has_more = True
    start_cursor = None
    
    while has_more:
        url = f"{BASE_URL}/blocks/{block_id}/children"
        params = {}
        if start_cursor:
            params["start_cursor"] = start_cursor
            
        response = requests.get(url, headers=NOTION_HEADERS, params=params)
        response.raise_for_status()
        data = response.json()
        
        for block in data.get("results", []):
            if block.get("has_children"):
                # Recursively fetch nested children
                block["children_blocks"] = get_page_blocks(block["id"])
            blocks.append(block)
            
        has_more = data.get("has_more", False)
        start_cursor = data.get("next_cursor")
        
    return blocks

def update_block(block_id: str, content: Dict[str, Any]) -> Dict[str, Any]:
    """更新某个块的内容（如富文本和样式 annotations）。"""
    url = f"{BASE_URL}/blocks/{block_id}"
    response = requests.patch(url, headers=NOTION_HEADERS, json=content)
    response.raise_for_status()
    return response.json()

def append_children(parent_id: str, children: List[Dict[str, Any]], after_id: str = None, position: str = None) -> Dict[str, Any]:
    """向给定的父块追加新的子块（用于插入 sub-task）。"""
    url = f"{BASE_URL}/blocks/{parent_id}/children"
    payload = {
        "children": children
    }
    if after_id:
        payload["after"] = after_id
    if position:
        payload["position"] = {"type": position}
        
    response = requests.patch(url, headers=NOTION_HEADERS, json=payload)
    response.raise_for_status()
    return response.json()

def replace_with_toggle(block_id: str, target_parent_id: str, toggle_content: Dict[str, Any], children: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    删除当前块并重新创建一个带相同子块的 Toggle 块。 
    Notion API 无法直接变更带子块的内容类型为 toggle。
    工作流：
    1. 在原块的父级下追加一个新的 toggle 块（含要迁移的内容和子节点）。
    2. 归档（Archive/Delete）原始的块。
    """
    # 1. 在父级块 (target_parent_id) 尾部追加这个全新的 toggle 块结构
    new_toggle_block = {
        "object": "block",
        "type": "toggle",
        "toggle": {
            "rich_text": toggle_content.get("rich_text", []),
            "color": toggle_content.get("color", "default"),
            "children": children
        }
    }
    append_res = append_children(target_parent_id, [new_toggle_block])
    
    # 获取刚追加进去的新块对象
    new_block = append_res.get("results", [])[-1]
    
    # 2. 归档老的旧块
    delete_block(block_id)
    
    return new_block

def replace_with_bullet(
    block_id: str,
    target_parent_id: str,
    rich_text: List[Dict[str, Any]],
    color: str = "default",
    children: List[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Replace a block with a bulleted_list_item under the same parent.
    Uses insert-after to preserve ordering, then deletes the original block.
    """
    bullet_payload = {
        "rich_text": rich_text,
        "color": color
    }
    if children:
        bullet_payload["children"] = children

    new_bullet_block = {
        "object": "block",
        "type": "bulleted_list_item",
        "bulleted_list_item": bullet_payload
    }
    append_res = append_children(target_parent_id, [new_bullet_block], after_id=block_id)
    new_block = append_res.get("results", [])[-1] if append_res.get("results") else {}
    delete_block(block_id)
    return new_block

def replace_with_toggle_item(
    block_id: str,
    target_parent_id: str,
    rich_text: List[Dict[str, Any]],
    color: str = "default",
    children: List[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Replace a block with a toggle under the same parent.
    Uses insert-after to preserve ordering, then deletes the original block.
    """
    if children is None:
        children = []

    toggle_payload = {
        "rich_text": rich_text,
        "color": color
    }
    if children:
        toggle_payload["children"] = children

    new_toggle_block = {
        "object": "block",
        "type": "toggle",
        "toggle": toggle_payload
    }
    append_res = append_children(target_parent_id, [new_toggle_block], after_id=block_id)
    new_block = append_res.get("results", [])[-1] if append_res.get("results") else {}
    delete_block(block_id)
    return new_block
    
def delete_block(block_id: str) -> Dict[str, Any]:
    """删除（归档）指定的块。"""
    url = f"{BASE_URL}/blocks/{block_id}"
    response = requests.delete(url, headers=NOTION_HEADERS)
    response.raise_for_status()
    return response.json()
